// <auto-generated />
namespace AutoLotDALEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Final : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Final));
        
        string IMigrationMetadata.Id
        {
            get { return "201907050626164_Final"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
