//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.iamchirag.com", ConfigurationName="ServiceReference1.MyMathService")]
    public interface MyMathService {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.iamchirag.com/MyMathService/Sum", ReplyAction="www.iamchirag.com/MyMathService/SumResponse")]
        int Sum(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.iamchirag.com/MyMathService/Sum", ReplyAction="www.iamchirag.com/MyMathService/SumResponse")]
        System.Threading.Tasks.Task<int> SumAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyMathServiceChannel : MathServiceClient.ServiceReference1.MyMathService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyMathServiceClient : System.ServiceModel.ClientBase<MathServiceClient.ServiceReference1.MyMathService>, MathServiceClient.ServiceReference1.MyMathService {
        
        public MyMathServiceClient() {
        }
        
        public MyMathServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyMathServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Sum(int x, int y) {
            return base.Channel.Sum(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SumAsync(int x, int y) {
            return base.Channel.SumAsync(x, y);
        }
    }
}
